
services:

  application:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: >
      /app/str_app.py --server.port 8080
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    # profiles:
    #   - app
    # if GPU is available, uncomment below section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities:
    #             - gpu